apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgress-deployment
  labels:
    name: postgres
spec:
  template:
    metadata:
      name: postgress
      labels:
        name: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:9.4
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
  selector:
    matchLabels:
      name: postgres
  replicas: 1
